version: '3'

services:
  backend:
    build:
      context: ./Server
      dockerfile: ./Dockerfile
    image: "blasphemous/my-portfolio-backend"
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./Client
      dockerfile: ./Dockerfile
    image: "blasphemous/my-portfolio-frontend"
    ports:
      - "3000:3000"